{
  "components": {
    "securitySchemes": {
      "ApiKeyAuth": {
        "in": "header",
        "name": "api_key",
        "type": "apiKey"
      }
    }
  },
  "info": {
    "description": "Domain manager launches static websites and categorizes domains",
    "title": "Domain Manager API",
    "version": "1.0.0"
  },
  "openapi": "3.0.0",
  "paths": {
    "/api/application/{application_id}/": {
      "delete": {
        "parameters": [
          {
            "in": "path",
            "name": "application_id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "Deletes an application",
        "tags": [
          "Applications"
        ]
      },
      "get": {
        "parameters": [
          {
            "in": "path",
            "name": "application_id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "_id": "12345d",
                    "name": "application name",
                    "requested_date": "2020-08-14T20:54:43.058000",
                    "requester_name": "user"
                  },
                  "type": "string"
                }
              }
            },
            "description": "Returns an application by its id"
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "Get a specific application by its id",
        "tags": [
          "Applications"
        ]
      },
      "put": {
        "parameters": [
          {
            "in": "path",
            "name": "application_id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "name": "Con-PCA"
                },
                "properties": {
                  "name": {
                    "type": "string"
                  }
                },
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "Updates an existing application",
        "tags": [
          "Applications"
        ]
      }
    },
    "/api/applications/": {
      "get": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": [],
                  "type": "string"
                }
              }
            },
            "description": "List of applications."
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "Get a list of applications",
        "tags": [
          "Applications"
        ]
      },
      "post": {
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "name": "Con-PCA"
                },
                "properties": {
                  "name": {
                    "type": "string"
                  }
                },
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "Adds a new application",
        "tags": [
          "Applications"
        ]
      }
    },
    "/api/categorize/{live_site_id}/": {
      "get": {
        "parameters": [
          {
            "in": "path",
            "name": "live_site_id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Categorize an active site's domain"
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "Categorize an active site's domain",
        "tags": [
          "Categorization"
        ]
      }
    },
    "/api/check/?domain={domain}": {
      "get": {
        "parameters": [
          {
            "in": "path",
            "name": "domain",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": {},
                  "type": "string"
                }
              }
            },
            "description": "Returns category details"
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "Check a domain's category on multiple proxies",
        "tags": [
          "Check Categories"
        ]
      }
    },
    "/api/domain/{domain_id}/": {
      "get": {
        "parameters": [
          {
            "in": "path",
            "name": "domain_id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": {},
                  "type": "string"
                }
              }
            },
            "description": "Returns domain details."
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "Get a registered domain by its id",
        "tags": [
          "Domains"
        ]
      },
      "put": {
        "parameters": [
          {
            "in": "path",
            "name": "domain_id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "tag_id": "get-tag-uuid"
                },
                "properties": {
                  "tag_id": {
                    "type": "string"
                  }
                },
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "Add a tag to a domain",
        "tags": [
          "Domains"
        ]
      }
    },
    "/api/domains/": {
      "get": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": [],
                  "type": "string"
                }
              }
            },
            "description": "List of domains"
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "Get a list of of registered domains",
        "tags": [
          "Domains"
        ]
      }
    },
    "/api/live-site/{live_site_id}/": {
      "delete": {
        "parameters": [
          {
            "in": "path",
            "name": "live_site_id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "Take down a live website",
        "tags": [
          "Live Websites"
        ]
      },
      "get": {
        "parameters": [
          {
            "in": "path",
            "name": "live_site_id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "_id": "12345",
                    "application": {
                      "_id": "12345",
                      "name": "DHS Red Team",
                      "requested_date": "2020-08-14T20:54:43.058000",
                      "requester_name": "dev_user"
                    },
                    "domain": {
                      "CallerReference": "123-456-789",
                      "Config": {
                        "Comment": "a comment",
                        "PrivateZone": false
                      },
                      "Id": "/hostedzone/123456",
                      "Name": "example.com.",
                      "ResourceRecordSetCount": 5,
                      "_id": "12345"
                    },
                    "is_categorized": false,
                    "is_email_active": false,
                    "launch_date": "2020-08-15T19:14:27.302000",
                    "name": "Dental-Surgeon",
                    "website": {
                      "_id": "12345",
                      "name": "Dental-Surgeon"
                    }
                  },
                  "type": "string"
                }
              }
            },
            "description": "Returns an live website by its id"
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "Get a specific live website by its id",
        "tags": [
          "Live Websites"
        ]
      },
      "put": {
        "parameters": [
          {
            "in": "path",
            "name": "live_site_id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "application_id": "get-application-uuid"
                },
                "properties": {
                  "application_id": {
                    "type": "string"
                  }
                },
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "Updates an existing live website",
        "tags": [
          "Live Websites"
        ]
      }
    },
    "/api/live-sites/": {
      "get": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": [],
                  "type": "string"
                }
              }
            },
            "description": "List of websites that are currently live."
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "Get a list of live websites",
        "tags": [
          "Live Websites"
        ]
      },
      "post": {
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "application_id": "insert-application-uuid",
                  "description": "add a description",
                  "domain_id": "insert-domain-uuid",
                  "ip_address": "insert-ip-address",
                  "website_id": "insert-website-uuid"
                },
                "properties": {
                  "application_id": {
                    "type": "string"
                  },
                  "domain_id": {
                    "type": "string"
                  },
                  "ip_address": {
                    "type": "string"
                  },
                  "website_id": {
                    "type": "string"
                  }
                },
                "required": [
                  "domain_id",
                  "application_id"
                ],
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "Launches a live website",
        "tags": [
          "Live Websites"
        ]
      }
    },
    "/api/proxies/": {
      "get": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": [],
                  "type": "string"
                }
              }
            },
            "description": "List of proxies."
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "Get a list of proxies",
        "tags": [
          "Proxies"
        ]
      },
      "post": {
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "categories": [
                    "Health",
                    "Chat",
                    "Finance"
                  ],
                  "name": "Trusted Source",
                  "script": "driver.find_element()",
                  "url": "https://exampleproxy.com"
                },
                "properties": {
                  "name": {
                    "type": "string"
                  }
                },
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "Adds a new proxy",
        "tags": [
          "Proxies"
        ]
      }
    },
    "/api/proxy/{proxy_id}/": {
      "delete": {
        "parameters": [
          {
            "in": "path",
            "name": "proxy_id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "Deletes a proxy",
        "tags": [
          "Proxies"
        ]
      },
      "get": {
        "parameters": [
          {
            "in": "path",
            "name": "proxy_id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "_id": "12345d",
                    "name": "proxy name",
                    "requested_date": "2020-08-14T20:54:43.058000",
                    "requester_name": "user"
                  },
                  "type": "string"
                }
              }
            },
            "description": "Returns a proxy by its id"
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "Get a specific proxy by its id",
        "tags": [
          "Proxies"
        ]
      },
      "put": {
        "parameters": [
          {
            "in": "path",
            "name": "proxy_id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "name": "Trusted Source"
                },
                "properties": {
                  "name": {
                    "type": "string"
                  }
                },
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "Updates an existing proxy",
        "tags": [
          "Proxies"
        ]
      }
    },
    "/api/tag/{tag_id}/": {
      "delete": {
        "parameters": [
          {
            "in": "path",
            "name": "tag_id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "Deletes a domain tag",
        "tags": [
          "Tags"
        ]
      },
      "get": {
        "parameters": [
          {
            "in": "path",
            "name": "tag_id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "_id": "12345d",
                    "name": "tag name"
                  },
                  "type": "string"
                }
              }
            },
            "description": "Returns an tag by its id"
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "Get a specific domain tag by its id",
        "tags": [
          "Tags"
        ]
      },
      "put": {
        "parameters": [
          {
            "in": "path",
            "name": "tag_id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "name": "Red Team"
                },
                "properties": {
                  "name": {
                    "type": "string"
                  }
                },
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "Updates an existing domain tag",
        "tags": [
          "Tags"
        ]
      }
    },
    "/api/tags/": {
      "get": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": [],
                  "type": "string"
                }
              }
            },
            "description": "List of domain tags."
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "Get a list of domain tags",
        "tags": [
          "Tags"
        ]
      },
      "post": {
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "name": "Red Team"
                },
                "properties": {
                  "name": {
                    "type": "string"
                  }
                },
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "Adds a new domain tag",
        "tags": [
          "Tags"
        ]
      }
    },
    "/api/website/{website_id}/": {
      "get": {
        "parameters": [
          {
            "in": "path",
            "name": "website_id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": {},
                  "type": "string"
                }
              }
            },
            "description": "Returns website details."
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "Get website content by its id",
        "tags": [
          "Websites"
        ]
      }
    },
    "/api/websites/": {
      "get": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": [],
                  "type": "string"
                }
              }
            },
            "description": "List of available s3 websites"
          }
        },
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "Get a list of website content",
        "tags": [
          "Websites"
        ]
      }
    }
  }
}
